### ISSUE TITLE
Issue about commend line operation

### ISSUE THREAD

**Issue by hxyv** [deepomicslab/PhageScope#1]
Hello, nice job! Does your PhageScope provide command-line operations? Because we have data on a Linux server, if the tools can provide command-line operations, it can be much more convenient.

**Comment by wangruohan111** [comment]
Hi, thanks for your interest in PhageScope. Currently, PhageScope does not support command-line operations, but the uploaded fasta file (<10MB) could contain multiple phage sequences, and PhageScope will return the annotations for all the sequences.
