### ISSUE TITLE
Regarding PhageScope database

### ISSUE THREAD

**Issue by ShailNair** [deepomicslab/PhageScope#2]
Hi,
Congratulations on the PhageScope article and thank you for establishing a much-needed extensive database. I have a few queries:

1. The article mentions that sequences were searched in the respective database using keywords such as 'phage,' 'bacteriophage,' and 'virus.' Does this mean PhageScope do not contain viruses other than bacteriophages?

2. How were bacteriophages identified? If identification relied on taxonomic/genomic similarities, does this imply that PhageScope excluded many phage sequences from other databases that remained unassigned?

3. Many thanks for providing access to the genomes and proteins with annotations on [PhageScope server](https://phagescope.deepomics.org/download). However, the provided databases are from datasets such as IMGVR, RefSeq, and others used to construct PhageScope. It would have been nice if the non-redundant PhageScope database was available for download.

Thank you

**Comment by wangruohan111** [comment]
Hi,

Sorry for the late response. Here are my answers to your queries.

1. Yes, the current version of PhageScope only contains bacteriophages.
2. PhageScope collected phage sequences from public resources; it didn't identify phages on its own. 
3. Thanks for the suggestion, we would like to have updates in the following versions. Currently you may find the non-redundant sequences on https://phagescope.deepomics.org/database/phage with the "Hide redundancy" option.

Thanks for your interest in PhageScope!
