### ISSUE TITLE
lifestyle prediction fails

### ISSUE THREAD

**Issue by dejsha** [deepomicslab/PhageScope#3]
Hi, 
I am not able to run lifestyle prediciton analysis.
The task always fails (tasks 7384, 7385, 7456). 
The log always says:

/var/spool/slurmd/job1417095/slurm_script: line 19: ${$2}: bad substitution
/apps/software/SciPy-bundle/2021.10-foss-2021b/lib/python3.9/site-packages/pythran/tables.py:4520: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  if not hasattr(numpy, method):
/apps/software/SciPy-bundle/2021.10-foss-2021b/lib/python3.9/site-packages/pythran/tables.py:4553: FutureWarning: In the future `np.bytes` will be defined as the corresponding NumPy scalar.
  obj = getattr(themodule, elem)
Traceback (most recent call last):
  File "/data2/platform/phage_database/analysis_script/lifestyle/Graphage_lifestyle.py", line 18, in <module>
    import Biodata
  File "/data2/platform/phage_database/analysis_script/lifestyle/Biodata.py", line 7, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
module load complete
running build_ext
task complete

Could you please check what is the problem?
Thank you very much!!
Dagmar

**Comment by ys2022** [comment]
Dear Dagmar,

Thank you for reporting the issues. We have identified a compatibility issue with PyTorch following a recent upgrade. Our team is working to resolve this and we expect to deploy a fix within the next two days.

We apologize for the inconvenience and appreciate your patience.

Best regards,
PhageScope Team

**Comment by ys2022** [comment]
Dear Dagmar,

The issue has been resolved. If you encounter any further problems, please do not hesitate to contact us.

Best regards,
PhageScope Team
